# Generated by Django 4.1.1 on 2022-10-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="archivo", name="uploaded_at",),
    ]
